### ISSUE TITLE
Missing feature : Alpha Transparency from blender to JME

### ISSUE THREAD

**Issue by Ali-RS** [xbuf/blender_io_xbuf#4]
This is about adding support for importing Alpha transparent texture from blender to JME: 
with no alpha : 
![noalpha](https://cloud.githubusercontent.com/assets/5787647/15359444/3c74a3ca-1cbe-11e6-9da9-2e1d1fd474f7.png)
with alpha : 
![withalpha](https://cloud.githubusercontent.com/assets/5787647/15359463/5025db1e-1cbe-11e6-8277-3f9b76ccb06b.png)

This is my Diffuse texture with alpha (In my case Diffuse and Alpha map are same but they can be different)
![txture](https://cloud.githubusercontent.com/assets/5787647/15362833/72e97234-1ccb-11e6-8c78-4119b58e5068.png)

because wiki page is down yet please take look at
http://web.archive.org/web/20151026120758/http://wiki.jmonkeyengine.org/doku.php/jme3:intermediate:how_to_use_materials
to see how Transparency works in jme material.
FYI: 

```
getAdditionalRenderState().setAlphaTest(true)
getAdditionalRenderState().setAlphaFallOff(0.5f);
```

is deprecated in jme 3.1 and you should use `mat.setFloat("AlphaDiscardThreshold", 0.1f);`
by default AlphaDiscardThreshold=0.1 will be enough in 99% of situation but it might be better to let user set it in blender.
so you may need to add a new field like "AlphaDiscardThreshold"  in Texture panel under tab "Influence" to let user set it.

also this post might be useful: https://hub.jmonkeyengine.org/t/solved-need-help-with-alpha-channel-for-texture/34724/2

**Comment by Ali-RS** [comment]
Any idea @davidB  ?

**Comment by davidB** [comment]
I'll take a look. but before I have to update and add your case into https://github.com/xbuf/jme3_xbuf/blob/master/samples/unittest/xbuf_unittest.blend. It's a blend scene with one object per stuff I want to test. After working with various model, I decide to use this single blend to store/to track every case in isolation.
I'll take a look at your issue after work or next week-end. (Sorry for delay)

**Comment by Ali-RS** [comment]
Thanks.
 I am now testing the material parameters (transparency and ...) and how they should map from blender to jme material. I will put the result here. (I will do the test on your xbuf_unittest.blend)

**Comment by Ali-RS** [comment]
I added a simple cube test (Test.7.0 , Test.7.1) to your xbuf_unittest.blend. Can you please check it out ?
https://drive.google.com/file/d/0B35eWZpi0dBoOUxVaDJ4MGQ1aGM/view?usp=sharing

The thing you need to add to xbuf exporter is:
for Test.7.0: 
- check if transparency is on, on the material, then read Alpha number from there and set it to jme     material(for Lighting.j3md). this is how i do it in java code : 

```
mat.getAdditionalRenderState().setBlendMode(RenderState.BlendMode.Alpha);
mat.setBoolean("UseMaterialColors",true);
mat.setColor("Diffuse", new ColorRGBA(R,G,B, xx));//xx is the alpha you get from blender
```

![mattransparent](https://cloud.githubusercontent.com/assets/5787647/15398586/0dc829da-1d99-11e6-85cd-b9c47776eec9.png)

for Test.7.1 : 
-  if Diffuse map and Alpha map textures are the same 

![dif_alph_same](https://cloud.githubusercontent.com/assets/5787647/15398834/12bc2814-1d9a-11e6-8607-21bcb2ae71af.png)
then you just need to : `mat.setFloat("AlphaDiscardThreshold", 0.1f);` 
- if Diffuse map and Alpha map textures are **_NOT_** the same 
  ![diff_alpha_not_same](https://cloud.githubusercontent.com/assets/5787647/15399111/3dc40ad0-1d9b-11e6-9f22-1c7a3c1e23b7.png)

then you need to first set Alpha map to material parameter for j3m and then apply AlphaDiscardThreshold.
This is how i do in java : 

```
mat.setTexture("AlphaMap", assetManager.loadTexture(tk));
mat.setFloat("AlphaDiscardThreshold", 0.1f);
```

Any question ?

Thanks

**Comment by Ali-RS** [comment]
And these are some screenshots in jme 3.1 : 
`mat.setBoolean("UseMaterialColors",true);   mat.getAdditionalRenderState().setBlendMode(RenderState.BlendMode.Off);`
![blend_off](https://cloud.githubusercontent.com/assets/5787647/15408268/2b93054a-1dc4-11e6-9136-3eecdb58cc8a.png)

```
mat.getAdditionalRenderState().setBlendMode(RenderState.BlendMode.Alpha);
 mat.setBoolean("UseMaterialColors",true);                         
 mat.setColor("Diffuse", new ColorRGBA(1,1,1,0.3f));
```

![blend_alpha](https://cloud.githubusercontent.com/assets/5787647/15408350/ae5dfcf0-1dc4-11e6-8cae-a03c5da84a5d.png)

```
mat.setBoolean("UseMaterialColors",true);   
mat.setFloat("AlphaDiscardThreshold", 0.1f); 
```

![alphasiscardthreshold_0 01](https://cloud.githubusercontent.com/assets/5787647/15408506/6adc764a-1dc5-11e6-8595-8b3923aeeee4.png)

```
mat.setBoolean("UseMaterialColors",true);   
mat.getAdditionalRenderState().setBlendMode(RenderState.BlendMode.Additive);
```

![ublend_additive](https://cloud.githubusercontent.com/assets/5787647/15408718/7154f91a-1dc6-11e6-9c87-c7d578e27055.png)

**Comment by davidB** [comment]
Thanks for all this info (code, image, .blend).
I started the integration of your unittest (I move them into to 1.6 and 1.7, section 1 is for texture).
I hope to do some progress on it this weekend.

**Comment by Ali-RS** [comment]
Thanks.

**Comment by davidB** [comment]
Sorry, I didn' work on the issue. (I work on the jme's wiki , previous WE, And I'm very busy this week, (unplanned urgent tasks). But I don't forgot, I'll work on it ASAP.

**Comment by Ali-RS** [comment]
Ah, I see. No problem.
Actually I check this github repo every day. :smile:  I thought you might forget about it. Glad to see you did not forget. :smiley: 
And thanks a lot for fixing wiki's problem.
Best wish

**Comment by Ali-RS** [comment]
Hi @davidB 
sorry to bring this up ..  
Any Progress Yet ? 

I had one more suggestion : It is about importing Hardness/Shininess(in JME Material)  
![untitled](https://cloud.githubusercontent.com/assets/5787647/15991345/4e7d5d54-3065-11e6-8ec1-bc9a65c64e2e.png)

Need to set "Hardness" value from blender directly to "Shininess" in Lighting.j3md material.

**Comment by davidB** [comment]
Hi,

No real progress on transparency, but we progress on pre-requirement (on jme3 side: loader2 become loader). 
jme's Shininess is bind to blender "Specular Intentisy".

**Comment by Ali-RS** [comment]
> jme's Shininess is bind to blender "Specular Intentisy".

Ah Yes. I just checked it . I set hardness to 450 in blender then exported to .xbuf and loaded in JME. then extracted material as .j3m and Shininess was set to 450 exactly. You just forgot to check the "UseMaterialColors" to true when exporting to xbuf .

**Comment by Ali-RS** [comment]
A better way might be to check if shininess is > 1 then enable UsematerialColors . Because if it is < = 1 then has no effect in material .

**Comment by MeFisto94** [comment]
Bumping this :smile:
Are we missing some Specifications in XBuf related to ~~animation~~ transparency or is this simply not entirely implemented in the xbuf-loader?

edit: Didn't want to talk about animation here :see_no_evil:

**Comment by davidB** [comment]
Animation is not part of the core xbuf, because I saw/experiment several
way to express animation. So animations are part of extensions, today there
is only
https://github.com/xbuf/xbuf/blob/master/src/main/proto/xbuf_ext/animations_kf.proto
to define animation.
btw, please, open an other ticket to discuss animation.

**Comment by MeFisto94** [comment]
Embarrassing... of course I wanted to say transparency... Might have been the "Alpha" which distracted me during typing...

So regarding transparency:
Are we missing the logic which sets Material Parameters, or is there no way for us to see the BlendMode or the "influence parameter" (which jme doesn't seem to have anyway)?

**Comment by davidB** [comment]
push an experimental support of transparency into
- blender exporter (export alpha like opacity)
- jme importer (no AlphaMap => use BlendMode.AdditiveAlpha, with AlphaMap => use alpha/opacity as AlphaThreshold). I'm not a big fan on this, but it should fixe common usage.

**Comment by Ali-RS** [comment]
Thanks a lot from both of you.

**Comment by Ali-RS** [comment]
"UseMaterialColors" is not enabled in jme material when importing model. What should I enable in blender so I have it enabled ?

**Comment by Ali-RS** [comment]
Material Parameter "UseMaterialColors" is not enabled by default when importing .xbuf to jme. What should I enable in blender so I have it enabled in jme side ?

**Comment by davidB** [comment]
In Blender, to have UseMaterialColors in jme : 
- shadeless unchecked
- no Texture for Diffuse (aka no ColorMap in jm3d)
- Vertex Color Paint unchecked
- Diffuse color set

see  https://github.com/xbuf/jme3_xbuf/blob/master/jme3_xbuf_loader/src/main/java/jme3_ext_xbuf/mergers/MaterialsMerger.java#L187

**Comment by Ali-RS** [comment]
If Diffuse texture and Alpha texture **_are the same_** textureSlot then you should only apply alphaDiscardThreshold and NOT set AlphaMap in JME material . Setting it will cause transparency issue : (tried it on two model and both had trancparency issue ) 
![untitled](https://cloud.githubusercontent.com/assets/5787647/16633899/3a7665ac-4380-11e6-84b5-9010294ef6c4.png)

after clearing AlpaMap parameter from material the issue is gone : (mat.clearParam("AlphaMap"))
![untitled](https://cloud.githubusercontent.com/assets/5787647/16634148/48234e12-4381-11e6-8cff-a91bceca9e5e.png)

**Comment by davidB** [comment]
If your Diffuse texture include alpha, you don't need to set it as alpha texture, simply tell the material to use alpha.

**Comment by Ali-RS** [comment]
> no Texture for Diffuse (aka no ColorMap in jm3d)

Why ? If UseMaterialColor is not enabled then I will lose the specularity (shininess).
I can set ColorMap in JME material and in the meanwhile enable the MaterialColor

**Comment by Ali-RS** [comment]
> If your Diffuse texture include alpha, you don't need to set it as alpha texture, simply tell the material to use alpha.

It will make the whole model looks transparent and i will have no AlphaDiscardThreshold applied.

**Comment by Ali-RS** [comment]
>  simply tell the material to use alpha.

Do you mean to just set alpha : 
![untitled](https://cloud.githubusercontent.com/assets/5787647/16635128/c5f999dc-4385-11e6-949a-724bd632a8e4.png)

As i said it makes whole material transparent.

**Comment by davidB** [comment]
> Why ? In this way I will lose the light reflection (specularity)
> I can set ColorMap in JME material and in the meanwhile enable the MaterialColor

I searching ...

> It will make the whole model looks transparent and i will have not AlphaDiscardThreshold.

not the whole model. but it make the black (0,0,0) invisible (may be due to my misused of additive).
it should use the alpha from the image.

Anyway.  I'll investigate deeper (why your letter black letter A is invisible,....)
And I'll review the to way it's binding and try to improve.

(sorry I've issur to upload image on imgur)

**Comment by Ali-RS** [comment]
Edit : 

> If UseMaterialColor is not enabled then I will lose the specularity (shininess).

**Comment by Ali-RS** [comment]
In the case if Diffuse and Alpha are the same texture If You do not set AlphaMap for material and just set alphaDiscardThreshold then every thing will work as it is supposed to work.
And set the UseMaterialColor to be always ON. (Ogre and Blender importer for JME are doing this) 
JME will check if the shininess is <= 1 the the model will look like if there is no specularity but if shininess  >1 then JME will apply shininess on it.

**Comment by davidB** [comment]
> In the case if Diffuse and Alpha are the same texture If You do not set
> AlphaMap for material and just set alphaDiscardThreshold then every thing
> will work as it is supposed to work.

Blender (and xbuf) doesn't have the notion of alphaDiscardThreshold. They
only have factor/coeff, no threshold.

> And set the UseMaterialColor to be always ON. (Ogre and Blender importer
> for JME are doing this)

No , for vertex color/ (vertex paint) UseMaterialColor should be off/unset

**Comment by Ali-RS** [comment]
This edit in `MaterialsMerger.java` fixed the issue : 

```
  if(src.hasOpacityMap() && src.hasColorMap() )
                {
                    //Not setting AlphaMap if ColorMap(DiffuseMap) and OpacityMap(AlphaMap) are the same. 
                    if(! src.getColorMap().getRpath().equals(src.getOpacityMap().getRpath()))
                    {
                        setTexture2D(src.hasOpacityMap(),src.getOpacityMap(),dst,new String[]{"AlphaMap","OpacityMap"},md);
                    }
                }
```

```
if(!src.getShadeless()){
            //"UseMaterialColors" can also be enabled even if material has ColorMap.
                        //if(!src.hasColorMap()){ 
                if(src.hasColor()){
                    setBoolean(true,true,dst,new String[]{"UseMaterialColors"},md);
                }else{
                    setBoolean(true,true,dst,new String[]{"UseVertexColor"},md);
                }
            //}
        }
```

**Comment by davidB** [comment]
> //Not setting AlphaMap if ColorMap(DiffuseMap) and OpacityMap(AlphaMap) are the same. 
>                   if(! src.getColorMap().getRpath().equals(src.getOpacityMap().getRpath()))

is the same as not check the "Diffuse > Alpha" in the texture panel

**Comment by Ali-RS** [comment]
> is the same as not check the "Diffuse > Alpha" in the texture panel

in this case this line will never get executed : 

```

if (src.hasOpacityMap()) {
                    setFloat(src.hasOpacity(),src.getOpacity(),dst,new String[]{"AlphaDiscardThreshold"},md);
                    //dst.getAdditionalRenderState().setBlendMode(BlendMode.Alpha);
                }
```

Yes this solution seems to be cheap and not a proper way and it is not a problem from Xbuf but  because JME's material do something wrong in the case DiffuseMap and AlphaMap are in the same texture or may be I should separate Alpha channel from Diffuse texture to make it works properly.

**Comment by davidB** [comment]
As I said, none of the value in blender is really AlphaDiscardThreshold
It was my mistake to try to set this value from the "existing" field on
blender.
AlphaDiscardThreshold is something different that the alpha values that you
can put in blender "panel"
I'll test if it can be set via Custom Properties on blender side.
