### ISSUE TITLE
Option for exporting only selected

### ISSUE THREAD

**Issue by Ali-RS** [xbuf/blender_io_xbuf#7]
Hi

Tried to merge this commit https://github.com/riccardobl/blender_io_xbuf/commit/91357c6cc2f0a60d2f3d0994325e0f29f821cf91 from @riccardobl's fork to mine (which is same as master from xbuf/blender_io_xbuf) then installed it on blender but when wanting to enable addon in blender addons page it gives this error : 
![xbuf-addon](https://cloud.githubusercontent.com/assets/5787647/17260539/dd2f457c-5585-11e6-8d47-79d49e4c9265.png)

Can you please help

**Comment by Ali-RS** [comment]
Never Mind. 
My question was embarrassing, sorry .
The problem was because of an extra space in line 1382 in python code. 
Never used python before. 
but how is it possible to throw an error just because of an extra space !!!

**Comment by riccardobl** [comment]
Because python uses indentation to divide code blocks instead of { }... and yes it's a questionable design choice.

And since you reminded me about this, i want to ask if we can add this feature officially. @davidB

**Comment by Ali-RS** [comment]
Thanks my friend. 
By walking through David's and your codes , I learned a lot. :smiley:

**Comment by Ali-RS** [comment]
@davidB 
no idea !? (about supporting this feature officially)

**Comment by davidB** [comment]
If you want to export only a set of objects, you should enable/disable the render state (the camera column in scene explorer).

Else to select only some material, some ... I don't know. An important point for me is that the export should be reproductible (from command line or savable preference).
