### ISSUE TITLE
problem in exporting custom properties on object

### ISSUE THREAD

**Issue by Ali-RS** [xbuf/blender_io_xbuf#9]
Hi
getting this error when exporting to xbuf.This happens when I add custom properties on object. (It works OK for material)
![customprop](https://cloud.githubusercontent.com/assets/5787647/17376269/1dfa7b9c-59ca-11e6-877c-e05929c2e6e4.png)

thanks

**Comment by riccardobl** [comment]
May be introduced by this commit: https://github.com/xbuf/blender_io_xbuf/commit/f6dd8b6362feffae0c0b0045a8a2a55946a54af3

**Comment by Ali-RS** [comment]
@riccardobl  @davidB 

The problem is in line [230](https://github.com/xbuf/blender_io_xbuf/blob/f6dd8b6362feffae0c0b0045a8a2a55946a54af3/xbuf_export.py#L230). 

```
def export_all_physics(scene, data, cfg):
    for obj in scene.objects:
        phy_data = None
        phy_data = export_rb(obj, phy_data, data, cfg)
        export_rbct(obj, phy_data, data, cfg)
       export_customproperties(obj, phy_data, data, cfg)
```

commented line `# export_customproperties(obj, phy_data, data, cfg)`, and the error is gone. now i am able to get added custom property as a UserData in jme side.
